const MESSAGE_BOX_COLOR_PRIMARY = 'bg-primary'
const MESSAGE_BOX_COLOR_POSITIVE = 'bg-positive'
const MESSAGE_BOX_COLOR_WARNING = 'bg-warning'
const MESSAGE_BOX_COLOR_NEGATIVE = 'bg-negative'

export default {
    MESSAGE_BOX_COLOR_PRIMARY,
    MESSAGE_BOX_COLOR_POSITIVE,
    MESSAGE_BOX_COLOR_WARNING,
    MESSAGE_BOX_COLOR_NEGATIVE
}